# SPDX-FileCopyrightText: 2025 SÃ©bastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

continue-on-failure = true

[[operations]]
include-path-regex = "/sync/?.*"
enabled = false

[auth]
basic = { username = "plain", password = "${RELAY_PASSWORD}" }
